### ISSUE TITLE
update .bazelversion to 2.2.0

### ISSUE THREAD

**Issue by didier-durand** [google/jsinterop-generator#41]
I installed last version of Bazel on my Mac : it is 2.2.0.

When I launch project build command, it fails because .bazelversion is currently in master at 1.0.0 

Can you upgrade to .bazelversion to 2.2.0? 
I did it on my machine and it works fine: I get "INFO: Build completed successfully, 233 total actions"

Thanks!
Didier

**Comment by gkdn** [comment]
Hi. Thanks for checking if it works with this project.
We need to update all related projects together so it may take a little while longer.
Being said that you can also use 'bazelisk' which chooses the version of bazel based on this version file.

**Comment by didier-durand** [comment]
Hi Goktug, thanks. I didn't know of bazelisk but I will use it from now on. Didier

**Comment by jDramaix** [comment]
fixed by 5e955f439a27881e92fd84340729322eecf16f49

**Comment by didier-durand** [comment]
Merci!
